VARIABLE_MAPPING = {
    'MAIN.m_container.m_stack.o_slidingCylinder.DI_Extended': 'stackslidingCylinderExtended',
    'MAIN.m_container.m_stack.o_slidingCylinder.DI_Retracted': 'stackslidingCylinderRetracted',
    'MAIN.m_container.m_stack.o_slidingCylinder.DO_Extend': 'stackslidingCylinderExtend',
    'MAIN.m_container.m_crane.o_MonostableCylinder.DI_Extended': 'craneMonostableCylinderExtended',
    'MAIN.m_container.m_crane.o_MonostableCylinder.DI_Retracted': 'craneMonostableCylinderRetracted',
    'MAIN.m_container.m_crane.o_MonostableCylinder.DO_Extend': 'craneMonostableCylinderExtend',
    'MAIN.m_container.m_crane.o_VacuumGripper.DI_TakenIn': 'craneVacuumGripperTakenIn',
    'MAIN.m_container.m_crane.m_PresenceSensorAtStack.DI_WPDetected': 'cranePresenceSensorAtStackWPDetected',
    'MAIN.m_container.m_crane.m_PresenceSensorAtConveyor.DI_WPDetected': 'cranePresenceSensorAtConveyorWPDetected',
    'MAIN.m_container.m_crane.m_PresenceSensorAtStamp.DI_WPDetected': 'cranePresenceSensorAtStampWPDetected',
    'MAIN.m_container.m_crane.Motor.DO_TurnClockwise': 'craneMotorTurnClockwise',
    'MAIN.m_container.m_crane.Motor.DO_TurnCounterclockwise': 'craneMotorTurnCounterclockwise',
    'MAIN.m_container.m_stamp.m_stampingCylinder.DI_Extended': 'stampstampingCylinderExtended',
    'MAIN.m_container.m_stamp.m_stampingCylinder.DO_Extend': 'stampstampingCylinderExtend',
    'MAIN.m_container.m_stamp.m_stampingCylinder.DI_Retracted': 'stampstampingCylinderRetracted',
    'MAIN.m_container.m_stamp.m_slidingCylinder.DI_Extended': 'stampslidingCylinderExtended',
    'MAIN.m_container.m_stamp.m_slidingCylinder.DI_Retracted': 'stampslidingCylinderRetracted',
    'MAIN.m_container.m_stamp.m_slidingCylinder.DO_Extend': 'stampslidingCylinderExtend',
    'MAIN.m_container.m_stamp.m_slidingCylinder.DO_Retract': 'stampslidingCylinderRetract',
    'MAIN.m_container.m_LSC.Motor.DO_TurnClockwise': 'LSCMotorTurnClockwise',
    'MAIN.m_container.m_LSC.m_rampPusherStart.DI_Retracted': 'LSCrampPusherStartRetracted',
    'MAIN.m_container.m_LSC.m_rampPusherMid.DI_Retracted': 'LSCrampPusherMidRetracted',
    'MAIN.m_container.m_LSC.m_rampPusherStart.DO_Extend': 'LSCrampPusherStartExtend',
    'MAIN.m_container.m_LSC.m_rampPusherMid.DO_Extend': 'LSCrampPusherMidExtend',
    'MAIN.m_container.m_LSC.m_Switch.DO_Extend': 'LSCSwitchExtend'
}
